version: '3'
services:
  py:
    container_name: py
    build:
      context: ./docker/py
    ports:
      - "8008:8000"
    volumes:
      - ./app:/app
    depends_on:
      - mysql

  mysql:
    build:
       context: ./docker/mysql
    container_name: mysql
    environment:
      MYSQL_DATABASE: '${MYSQL_DATABASE}'
      MYSQL_USER: '${MYSQL_USER}'
      MYSQL_PASSWORD: '${MYSQL_PASSWORD}'
      MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
      LANG: C.UTF_8
    ports:
      - "3306:3306"