version: '3'
services:
  py:
    container_name: na_py
    restart: always
    build:
      context: ./docker/py
    ports:
      - "8008:8000"
    volumes:
      - ./app:/app
    depends_on:
      - mysql
    networks:
      - noticer

  mysql:
    container_name: na_mysql
    restart: always
    build:
       context: ./docker/mysql
    environment:
      MYSQL_DATABASE: '${MYSQL_DATABASE}'
      MYSQL_USER: '${MYSQL_USER}'
      MYSQL_PASSWORD: '${MYSQL_PASSWORD}'
      MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
      LANG: C.UTF_8
    ports:
      - "3306:3306"
    networks:
      - noticer

networks:
  noticer:
    external: true