version: '3'
services:
  py:
    container_name: py
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8008:8000"
    volumes:
      - ./app:/app
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_DATABASE: '${MYSQL_DATABASE}'
      MYSQL_USER: '${MYSQL_USER}'
      MYSQL_PASSWORD: '${MYSQL_PASSWORD}'
      MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
    ports:
      - "3306:3306"